package levigibson.fto3phase;

import java.util.*;

import static levigibson.fto3phase.Util.*;

/**
 * <h2>FtoCoord</h2>
 * <h3>Overview</h3>
 * <p>FtoCoord is a static class that contains pruning tables and
 * move tables for each phase of solving the FTO. These tables are based
 * off compact lehmer indices generated by FtoCubie.java. These tables
 * make turning the FTO as easy as a few table lookups. In each phase
 * of solving the FTO, only the relevant information is packed into
 * the compact index, making the pruning tables / move tables as
 * small as possible. </p>
 * <h3>Move Tables</h3>
 * <p>Move tables are a 2-dimentional array. The arrays are indexed with</p>
 * <ul>
 *     <li>The current state (usually a big number)</li>
 *     <li>The move you want to apply</li>
 * </ul>
 * <p>The move table then returns the index of the state with the move applied.</p>
 * <h3>Pruning Tables</h3>
 * <p>The pruning tables are a single byte array that is indexed with the
 * current state. The pruning table returns the distance to solved.</p>
 * <h3>TxE Pruning (special pruning)</h3>
 * <p>The number of possible states for G2 edges and G2 triangles are
 * quite small. This solved takes advantage of this by combining the two
 * piece types into a single pruning table! The two compact indices are
 * combined and used to index the pruning table. There is no TxE move table.
 * That would take a lot of memory. Instead, the move lookups for the
 * triangles and edges are done separately, then combined for a pruning
 * lookup. </p>
 * <h3>Triple Pruning (special pruning)</h3>
 * <p>To prune the triples, each of the four triple colors are pruned separately.
 * The pruning is compacted into a single functions that takes the max pruning
 * value of the four colors</p>
 */
class FtoCoord {
    private static volatile boolean initialized;

    //-------------- Move Tables --------------//

    private static int[][] G1_EDGE_MOVES;
    private static int[][] G1_TRIANGLE_MOVES;

    private static int[][] G2_TRIANGLE_MOVES;
    private static int[][] G2_EDGE_MOVES;
    private static int[][] G2_TRIPLE_MOVES;

    private static int[][] G3_EDGE_MOVES;
    private static int[][] G3_CORNER_MOVES;

    //-------------- Pruning Tables --------------//

    private static byte[] g1Prun;

    private static byte[] g2TriplePrun;
    private static byte[] g2TxEPrun;

    private static byte[] g3CornerPrun;

    public static final int ALL_EDGES_SIZE = fact(12)/2;
    public static final int ALL_CORNER_PERMUTATION_SIZE = fact(6)/2;
    public static final int ALL_CORNER_ORIENTATION_SIZE = pow(2,5);
    public static final int ALL_TRIANGLE_SIZE = nCr(12,3) * nCr(9,3) * nCr(6,3);
    public static final int G1_TRIANGLES_SIZE = nCr(12,3);
    public static final int G1_EDGES_SIZE = nCr(12,3) * 2;
    public static final int G2_TRIANGLES_SIZE = nCr(9,3) * nCr(6,3);
    public static final int G2_EDGES_SIZE = nCr(9,3) * nCr(6,3) * 2 * 2;
    public static final int G2_TRIPLE_CORNER_SIZE = nCr(6,3) * pow(2,3);
    public static final int G2_TRIPLE_TRIANGLE_SIZE = nCr(12,3);
    public static final int G2_TRIPLE_SIZE = G2_TRIPLE_CORNER_SIZE * G2_TRIPLE_TRIANGLE_SIZE;
    public static final int G3_CORNERS_SIZE = (fact(6)/2) * pow(2,5);
    public static final int G3_EDGE_SIZE = pow(3,4);

    //-------------- Public Turn Functions --------------//

    /**
     * Apply a move to a g1 edge index generated by {@link  FtoCubie#g1PackEdges() g1PackEdges}
     * @param idx compact g1 edge index
     * @param move move 0-15
     * @return turned compact g1 edge index
     */
    public static int g1TurnEdges(int idx, int move){
        return G1_EDGE_MOVES[idx][move];
    }

    /**
     * Apply a move to a g1 triangle index generated by {@link  FtoCubie#g1PackTriangles() g1PackTriangles}
     * @param idx compact g1 triangle index
     * @param move move 0-15
     * @return turned compact g1 triangle index
     */
    public static int g1TurnTriangles(int idx, int move){
        return G1_TRIANGLE_MOVES[idx][move];
    }

    /**
     * Apply a move to a g2 triple index generated by {@link  FtoCubie#g2PackTriples(int) g2PackTriples}
     * @param idx compact g2 triple index
     * @param move move 0-15
     * @return turned compact g2 triple index
     */
    public static int g2TurnTriples(int idx, int move){
        return G2_TRIPLE_MOVES[idx][move];
    }

    /**
     * Apply a move to a g2 edge index generated by {@link  FtoCubie#g2PackEdges() g2PackEdges}
     * @param idx compact g2 edge index
     * @param move move 0-15
     * @return turned compact g2 edge index
     */
    public static int g2TurnEdges(int idx, int move){
        return G2_EDGE_MOVES[idx][move];
    }

    /**
     * Apply a move to a g2 triangle index generated by {@link  FtoCubie#g2PackTriangles() g2PackTris}
     * @param idx compact g2 triangle index
     * @param move move 0-15
     * @return turned compact g2 triangle index
     */
    public static int g2TurnTris(int idx, int move){
        return G2_TRIANGLE_MOVES[idx][move];
    }

    /**
     * Apply a move to a g3 edge index generated by {@link  FtoCubie#g3PackEdges() g3PackEdges}
     * @param idx compact g3 edge index
     * @param move move 0-15
     * @return turned compact g3 edge index
     */
    public static int g3TurnEdges(int idx, int move){
        return G3_EDGE_MOVES[idx][move];
    }

    /**
     * Apply a move to a g3 corner index generated by {@link  FtoCubie#g3PackCorners() g3PackCorners}
     * @param idx compact g3 corner index
     * @param move move 0-15
     * @return turned compact g3 corner index
     */
    public static int g3TurnCorners(int idx, int move){
        return G3_CORNER_MOVES[idx][move];
    }

    //-------------- Public Pruning Functions --------------//

    /**
     * Get the distance to solved for g1.
     * g1 is trivial and the entire state space can be stored in an array
     * bazinga!
     * @param edge index from {@link  FtoCubie#g1PackEdges() g1PackEdges}
     * @param tris index from {@link  FtoCubie#g1PackTriangles() g1PackTriangles}
     * @return distance from solved g1
     */
    public static int g1Prun(int edge, int tris){
        return g1Prun[packG1(edge, tris)];
    }

    /**
     * Get a lower bound for the distance to solved for the triples
     * Unlike the other pruning functions, this is not a hard-and-fast
     * distance to solved function. This is merely a heuristic that
     * creates a lower bound. This function can be used regularly to
     * prune.
     * @param idx1 triple index generated by {@link  FtoCubie#g2PackTriples(int) g2PackTriples}
     * @param idx2 triple index generated by {@link  FtoCubie#g2PackTriples(int) g2PackTriples}
     * @param idx3 triple index generated by {@link  FtoCubie#g2PackTriples(int) g2PackTriples}
     * @param idx4 triple index generated by {@link  FtoCubie#g2PackTriples(int) g2PackTriples}
     * @return lower bound for distance to solved for triples
     */
    public static int g2PrunTriple(int idx1, int idx2, int idx3, int idx4){
        int prun = 0;
        prun = Math.max(prun, g2TriplePrun[idx1]);
        prun = Math.max(prun, g2TriplePrun[idx2]);
        prun = Math.max(prun, g2TriplePrun[idx3]);
        prun = Math.max(prun, g2TriplePrun[idx4]);
        return prun;
    }

    /**
     * Get the distance to solved for the triangles and edges for G2
     * @param edge index from {@link  FtoCubie#g2PackEdges() g2PackEdges}
     * @param tris index from {@link  FtoCubie#g2PackTriangles() g2PackTris}
     * @return distance to solved triangles+edges for g2
     */
    public static int g2PrunTxE(int edge, int tris){
        return g2TxEPrun[packTxE(edge, tris)];
    }

    /**
     * Get the distance to solved for the corners for G3
     * @param corners index from {@link  FtoCubie#g3PackCorners() g3PackCorners}
     * @return distance fo solved for g3 corners
     */
    public static int g3PrunCorners(int corners){
        return g3CornerPrun[corners];
    }

    //-------------- Solve Check Functions --------------//

    public static final int SOLVED_G3_EDGES;
    public static final int SOLVED_G3_CORNERS;

    static {
        SOLVED_G3_EDGES = new FtoCubie().g3PackEdges();
        SOLVED_G3_CORNERS = new FtoCubie().g3PackCorners();
    }

    //-------------- Growable Primitive Int Array --------------//

    //Used in the BFS for pruning table generation
    private static class IntArray {
        int[] data;
        int size;

        IntArray(int capacity) {
            this.data = new int[capacity];
        }

        void add(int v) {
            if (size == data.length) {
                data = Arrays.copyOf(data, data.length * 2);
            }
            data[size++] = v;
        }

        void clear() {
            size = 0;
        }
    }

    //-------------- Pruning Table Generation --------------//

    private static int packG1(int edge, int tris){
        return edge * G1_TRIANGLES_SIZE + tris;
    }

    private static int turnG1(int idx, int move){
        int edge = idx / G1_TRIANGLES_SIZE;
        int tri = idx % G1_TRIANGLES_SIZE;

        edge = g1TurnEdges(edge, move);
        tri = g1TurnTriangles(tri, move);

        return packG1(edge, tri);
    }

    private static byte[] g1GeneratePrun() {
        final int size = G1_EDGES_SIZE * G1_TRIANGLES_SIZE;

        byte[] prun = new byte[size];
        Arrays.fill(prun, (byte) -1);

        //Since the initialization process is the same every time,
        //we know how big the frontier will get at its widest
        int MAX_FRONTIER_SIZE = 52063;

        //The max size of the frontier hard-coded here to save memory
        //IntArray is growable just in case :)
        IntArray frontier = new IntArray(MAX_FRONTIER_SIZE);
        IntArray next = new IntArray(MAX_FRONTIER_SIZE);

        FtoCubie solved = new FtoCubie();
        frontier.add(packG1(solved.g1PackEdges(), solved.g1PackTriangles()));
        prun[frontier.data[0]] = 0;

        int depth = 0;
        while (frontier.size > 0) {

            for (int i = 0; i < frontier.size; i++) {
                int idx = frontier.data[i];
                for (int move : Search.G1_MOVESET) {
                    int nextIdx = turnG1(idx, move);
                    if (prun[nextIdx] == -1) {
                        prun[nextIdx] = (byte) (depth + 1);
                        next.add(nextIdx);
                    }
                }
            }

            IntArray tmp = frontier;
            frontier = next;
            next = tmp;
            next.clear();

            depth++;
        }

        return prun;
    }

    /**
     * This function generates all the possible "solved" states
     * for a single triple color. All of these states are marked
     * as 0 moves from solved in the pruning table.
     * @return All solved triple states
     */
    private static IntArray g2GenerateTripleFrontier(){
        byte[] prun = new byte[G2_TRIPLE_SIZE];
        Arrays.fill(prun, (byte) -1);

        //Since the initialization process is the same every time,
        //we know how big the frontier will get at its widest
        int MAX_FRONTIER_SIZE = 100;
        int RETURN_ARRAY_SIZE = 161;

        //The max size of the frontier hard-coded here to save memory
        //IntArray is growable just in case :)
        IntArray all = new IntArray(RETURN_ARRAY_SIZE);
        IntArray next = new IntArray(MAX_FRONTIER_SIZE);
        IntArray frontier = new IntArray(MAX_FRONTIER_SIZE);

        frontier.add(new FtoCubie().g2PackTriples(0));

        while (frontier.size > 0) {
            for (int i = 0; i < frontier.size; i++) {
                all.add(frontier.data[i]);
            }

            for (int i = 0; i < frontier.size; i++) {
                int idx = frontier.data[i];
                for (int move : Search.G3_MOVESET) {
                    int nextIdx = G2_TRIPLE_MOVES[idx][move];
                    if (prun[nextIdx] == -1) {
                        prun[nextIdx] = (byte) (1);
                        next.add(nextIdx);
                    }
                }
            }

            IntArray tmp = frontier;
            frontier = next;
            next = tmp;
            next.clear();
        }

        return all;
    }

    private static byte[] g2GenerateTriplePrun() {
        byte[] prun = new byte[G2_TRIPLE_SIZE];
        Arrays.fill(prun, (byte) -1);

        //Since the initialization process is the same every time,
        //we know how big the frontier will get at its widest
        int MAX_FRONTIER_SIZE = 11484;

        //depth=0 frontier is all the states
        //where the colors are all matching
        IntArray frontier = g2GenerateTripleFrontier();
        for (int i = 0; i < frontier.size; i++) {
            prun[frontier.data[i]] = 0;
        }

        int depth = 0;
        while (frontier.size > 0) {
            IntArray next = new IntArray(MAX_FRONTIER_SIZE);

            for (int i = 0; i < frontier.size; i++) {
                int idx = frontier.data[i];
                for (int move : Search.G2_MOVESET) {
                    int nextIdx = G2_TRIPLE_MOVES[idx][move];
                    if (prun[nextIdx] == -1) {
                        prun[nextIdx] = (byte) (depth + 1);
                        next.add(nextIdx);
                    }
                }
            }
            frontier = next;
            depth++;
        }

        return prun;
    }

    //TxE state space is too big for a pruning table
    //so this is a hack to get around that
    //See TxE pruning info at the header of this class
    private static int packTxE(int edge, int tri){
        return edge * G2_TRIANGLES_SIZE + tri;
    }

    /**
     * Turn a compact index that contains information about
     * the g2 triangles and the g2 edges
     * @param idx index generated by { @link FtoCoord#packTxE(int, int) packTxe }
     * @param move Move to apply to the index
     * @return turned compact index
     */
    private static int turnTxE(int idx, int move){
        int edge = idx / G2_TRIANGLES_SIZE;
        int tri = idx % G2_TRIANGLES_SIZE;

        edge = g2TurnEdges(edge, move);
        tri = g2TurnTris(tri, move);

        return packTxE(edge, tri);
    }

    private static byte[] g2GenerateTxEPrun(){
        final int size = G2_EDGES_SIZE * G2_TRIANGLES_SIZE;

        byte[] prun = new byte[size];
        Arrays.fill(prun, (byte) -1);

        //Since the initialization process is the same every time,
        //we know how big the frontier will get at its widest
        int MAX_FRONTIER_SIZE = 4_194_993;

        //The max size of the frontier hard-coded here to save memory
        //IntArray is growable just in case :)
        IntArray frontier = new IntArray(MAX_FRONTIER_SIZE);
        IntArray next = new IntArray(MAX_FRONTIER_SIZE);

        FtoCubie solved = new FtoCubie();
        frontier.add(packTxE(solved.g2PackEdges(), solved.g2PackTriangles()));
        prun[frontier.data[0]] = 0;

        int depth = 0;
        while (frontier.size > 0) {
            for (int i = 0; i < frontier.size; i++) {
                int idx = frontier.data[i];

                for (int move : Search.G2_MOVESET) {
                    int nextIdx = turnTxE(idx, move);
                    if (prun[nextIdx] == -1) {
                        prun[nextIdx] = (byte) (depth + 1);
                        next.add(nextIdx);
                    }
                }
            }

            IntArray tmp = frontier;
            frontier = next;
            next = tmp;
            next.clear();

            depth++;
        }

        return prun;
    }

    private static byte[] g3GenerateCornerPrun(){
        byte[] prun = new byte[G3_CORNERS_SIZE];
        Arrays.fill(prun, (byte) -1);

        //Since the initialization process is the same every time,
        //we know how big the frontier will get at its widest
        int MAX_FRONTIER_SIZE = 5405;

        //The max size of the frontier hard-coded here to save memory
        //IntArray is growable just in case :)
        IntArray frontier = new IntArray(MAX_FRONTIER_SIZE);
        IntArray next = new IntArray(MAX_FRONTIER_SIZE);
        frontier.add(new FtoCubie().g3PackCorners());
        prun[frontier.data[0]] = 0;

        int depth = 0;
        while (frontier.size != 0) {
            for (int i = 0; i < frontier.size; i++) {
                int idx = frontier.data[i];
                for (int move : Search.G3_MOVESET) {
                    int nextIdx = g3TurnCorners(idx, move);
                    if (prun[nextIdx] == -1) {
                        prun[nextIdx] = (byte) (depth + 1);
                        next.add(nextIdx);
                    }
                }
            }
            IntArray tmp = frontier;
            frontier = next;
            next = tmp;
            next.clear();

            depth++;
        }

        return prun;
    }

    //-------------- Move Table Generation --------------//

    private static void g1InitEdges(){
        G1_EDGE_MOVES = new int[G1_EDGES_SIZE][16];
        FtoCubie fto = new FtoCubie();
        FtoCubie turned = new FtoCubie();

        for (int idx = 0; idx < G1_EDGES_SIZE; idx++) {
                fto.g1SetEdges(idx);
                int[] locMoves = G1_EDGE_MOVES[idx];

                for (int move : Search.G1_MOVESET) {
                    fto.turnInto(move, turned);
                    locMoves[move] = turned.g1PackEdges();
                }
        }
    }

    private static void g1InitTriangles(){
        G1_TRIANGLE_MOVES = new int[G1_TRIANGLES_SIZE][16];
        FtoCubie fto = new FtoCubie();
        FtoCubie turned = new FtoCubie();

        for (int idx = 0; idx < G1_TRIANGLES_SIZE; idx++) {
            fto.g1SetTriangles(idx);
            int[] moves = G1_TRIANGLE_MOVES[idx];

            for (int move : Search.G1_MOVESET) {
                fto.turnInto(move, turned);
                moves[move] = turned.g1PackTriangles();
            }
        }
    }

    private static void g2InitTris(){
        G2_TRIANGLE_MOVES = new int[G2_TRIANGLES_SIZE][10];
        FtoCubie fto = new FtoCubie();
        FtoCubie turned = new FtoCubie();

        for (int idx = 0; idx < G2_TRIANGLES_SIZE; idx++) {
            fto.g2SetTriangles(idx);
            int[] moves = G2_TRIANGLE_MOVES[idx];

            for (int move : Search.G2_MOVESET) {
                fto.turnInto(move, turned);
                moves[move] = turned.g2PackTriangles();
            }
        }
    }

    private static void g2InitEdges(){
        G2_EDGE_MOVES = new int[G2_EDGES_SIZE][10];
        FtoCubie fto = new FtoCubie();
        FtoCubie turned = new FtoCubie();

        for (int idx = 0; idx < G2_EDGES_SIZE; idx++) {
            fto.g2SetEdges(idx);
            int[] moves = G2_EDGE_MOVES[idx];

            for (int move : Search.G2_MOVESET) {
                fto.turnInto(move, turned);
                moves[move] = turned.g2PackEdges();
            }
        }
    }

    private static void g2InitTriples(){
        G2_TRIPLE_MOVES = new int[G2_TRIPLE_SIZE][10];
        FtoCubie fto = new FtoCubie();
        FtoCubie turned = new FtoCubie();

        for (int idx = 0; idx < G2_TRIPLE_SIZE; idx++) {
            fto.g2SetTriples(idx, 0);
            int[] moves = G2_TRIPLE_MOVES[idx];

            for (int move : Search.G2_MOVESET) {
                fto.turnInto(move, turned);
                moves[move] = turned.g2PackTriples(0);
            }
        }
    }

    private static void g3InitEdges(){
        G3_EDGE_MOVES = new int[G3_EDGE_SIZE][10];

        FtoCubie fto = new FtoCubie();
        FtoCubie turned = new FtoCubie();

        for (int idx = 0; idx < G3_EDGE_SIZE; idx++) {
            fto.g3SetEdges(idx);
            int[] moves = G3_EDGE_MOVES[idx];

            for (int move : Search.G3_MOVESET) {
                fto.turnInto(move, turned);
                moves[move] = turned.g3PackEdges();
            }
        }
    }

    private static void g3InitCorners(){
        G3_CORNER_MOVES = new int[G3_CORNERS_SIZE][10];

        FtoCubie fto = new FtoCubie();
        FtoCubie turned = new FtoCubie();

        for (int idx = 0; idx < G3_CORNERS_SIZE; idx++) {
            fto.g3SetCorners(idx);
            int[] moves = G3_CORNER_MOVES[idx];

            for (int move : Search.G3_MOVESET) {

                fto.turnInto(move, turned);
                moves[move] = turned.g3PackCorners();
            }
        }
    }

    //-------------- Public Initialization Functions --------------//

    public static boolean getInitialized(){
        return initialized;
    }

    public static synchronized void init(){
        if (initialized) {
            return;
        }

        g1InitEdges();
        g1InitTriangles();
        g1Prun = g1GeneratePrun();

        g2InitTris();
        g2InitEdges();
        g2InitTriples();
        g2TxEPrun = g2GenerateTxEPrun();
        g2TriplePrun = g2GenerateTriplePrun();

        g3InitEdges();
        g3InitCorners();
        g3CornerPrun = g3GenerateCornerPrun();

        initialized = true;
    }
}
